# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-21 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='FIO')),
                ('image', models.ImageField(upload_to='images/teachers', verbose_name='upload image')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number', models.CharField(max_length=255, verbose_name='Cell Phone Number')),
            ],
            options={
                'verbose_name': 'Teachers',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
